version: '3.3'

services:
  db:
    image: mongo:latest
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
        - MONGO_INITDB_ROOT_PASSWORD=#{DB_PASSWORD}
    ports:
      - "27017:27017"
